server-name test-sandbox

bind :8053

bind-http :8080
bind-tcp :8053

cache-size 4096
serve-expired yes
serve-expired-ttl 3600
serve-expired-reply-ttl 5

log-level debug

managed-dir /tmp/smartdns-managed
conf-dir /tmp/smartdns-conf

server-https https://dns.google/dns-query