# .github/workflows/nightly.yml
name: Nightly builds

on:  
  schedule:
    - cron:  '30 3 * * *'
  push:
    branches:
      - ci*

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
